site_name: Nimbus
site_url: https://nimbus.yoodule.com
site_description: Your 24/7 Employee
copyright: Created by <a href="mailto:sunday@yoodule.com">Sunday Johnson</a> for <a href="https://yoodule.com">Yoodule</a>

theme:
  name: material
  logo: static/favicon.svg
  favicon: static/favicon.svg
  palette:
    # Default to beautiful dark mode
    - scheme: slate
      primary: black
      accent: white
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
