site_name: Nimbus
site_url: https://nimbus.yoodule.com
site_description: Your 24/7 Employee
copyright: Built by <a href="https://www.linkedin.com/in/sundayj1213/" target="_blank">Sunday Johnson</a> at <a href="https://yoodule.com?utm_source=nimbus&utm_medium=docs&utm_campaign=footer">Yoodule</a>

theme:
  name: material
  logo: static/favicon.svg
  favicon: static/favicon.svg
  palette:
    # Default to beautiful dark mode
    - scheme: slate
      primary: black
      accent: white
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
