site_name: Nimbus
site_url: https://nimbus.yoodule.com
site_description: Your 24/7 Employee
copyright: Built by <a href="https://www.linkedin.com/in/sundayj1213/?utm_source=nimbus&utm_medium=docs&utm_campaign=footer" target="_blank">Sunday Johnson</a> at <a href="https://yoodule.com?utm_source=nimbus&utm_medium=docs&utm_campaign=footer">Yoodule</a>

extra_css:
  - extra.css

theme:
  name: material
  custom_dir: overrides
  logo: static/favicon.svg
  favicon: static/favicon.svg
  palette:
    # Default to beautiful dark mode
    - scheme: slate
      primary: black
      accent: white
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Download: download.md
  - Cloud: cloud.md
  - Official License: license.md
  - Terms of Service: terms_of_service.md
  - Privacy Policy: privacy_policy.md
